services:
  # app-service:
  #   build:
  #     context: ../src/
  #     dockerfile: ../src/PoC.KeyCloak.API/Dockerfile
  #   image: felipementel/keycloak-v1
  #   container_name: app-container
  #   restart: unless-stopped
  #   user: app
  #   ports:
  #     - 7457:99
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ASPNETCORE_HTTP_PORTS: 99
  #   depends_on:
  #     postgres-service:
  #       condition: service_healthy

  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin-service:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "80:80"

volumes:
  postgres-data:
  pgadmin-data: