name: 'PR Caller: Validate PR'
run-name: "PR Check by ${{ github.actor }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'src/**/_requests/**'

jobs:
  call-pr-check-workflow:
    name: Call PR Check Reusable Workflow
    uses: felipementel/reusable-workflows/.github/workflows/pr-check.yml@main
    permissions:
      contents: read
      security-events: write
    with:
      environment: 'DEV'
      gitLeaks: true
      sonarQube: true
      unitTests: true
      snyk: true
      msgCanalDeploy: 'PR Check - Canal DEPLOY'
      dotnetVersion: ${{ vars.DOTNETVERSION || '9.x' }}
      projectBaseDir: ${{ vars.PROJECTBASEDIR || './src' }}
      solutionFileName: ${{ vars.SOLUTIONFILENAME }}
      mainProject: ${{ vars.MAINPROJECT }}
      reportTitle: ${{ vars.REPORTTITLE || 'PR Check Report' }}
      sonarExclusions: ${{ vars.SONAREXCLUSIONS || '' }}
      imageName: ${{ vars.IMAGENAME }}
      openAPIFolder: "open-api"
    secrets:
      inherit
