name: Sanbox Dispatch ⚡
run-name: "${{ github.actor }} - ${{ github.run_id }}"

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docker/**'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to run the workflow'
        required: true
        default: 'DEV'
      git-leaks:
        type: boolean
        description: 'Run GitLeaks'
        required: false
        default: true
      sonar-qube:
        type: boolean
        description: 'Run SonarQube'
        required: false
        default: true
      unit-tests:
        type: boolean
        description: 'Run Unit Tests'
        required: false
        default: true
      snyk:
        type: boolean
        description: 'Snyk.io'
        required: false
        default: true
      msg-canal-deploy:
        type: string
        description: 'Message to be displayed in the summary'
        required: false
        default: 'Canal DEPLOY - O melhor canal sobre .NET, Azure, DevOps e IA'

env:
  dotnetVersion: 9.x
  projectBaseDir: ./src
  sln: DEPLOY.KeyCloak.sln
  mainProject: DEPLOY.KeyCloak.API
  reportTitle: 'Canal DEPLOY KeyCloak API'
  sonarExclusions: ""
  imageName: keycloak-v1

jobs:
  call-reusable-workflow:
    uses: felipementel/reusable-workflows/.github/workflows/sandbox.yml@main
    with:
      environment: ${{ inputs.environment }}
      git-leaks: ${{ inputs.git-leaks }}
      sonar-qube: ${{ inputs.sonar-qube }}
      unit-tests: ${{ inputs.unit-tests }}
      snyk: ${{ inputs.snyk }}
      msg-canal-deploy: ${{ inputs.msg-canal-deploy }}
      dotnetVersion: $dotnetVersion
      projectBaseDir: $env.projectBaseDir
      sln: $sln
      mainProject: $env.mainProject
      reportTitle: $env.reportTitle
      sonarExclusions: $env.sonarExclusions
      imageName: $imageName
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
