name: Sanbox Dispatch ⚡
run-name: "${{ github.actor }} - ${{ github.run_id }}"

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docker/**'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to run the workflow'
        required: true
        default: 'DEV'
      git-leaks:
        type: boolean
        description: 'Run GitLeaks'
        required: false
        default: true
      sonar-qube:
        type: boolean
        description: 'Run SonarQube'
        required: false
        default: true
      unit-tests:
        type: boolean
        description: 'Run Unit Tests'
        required: false
        default: true
      snyk:
        type: boolean
        description: 'Snyk.io'
        required: false
        default: true
      msg-canal-deploy:
        type: string
        description: 'Message to be displayed in the summary'
        required: false
        default: 'Canal DEPLOY - O melhor canal sobre .NET, Azure, DevOps e IA'

env:
  dotnetVersion: 9.x
  projectBaseDir: ./src
  sln: DEPLOY.KeyCloak.sln
  mainProject: DEPLOY.KeyCloak.API
  reportTitle: 'Canal DEPLOY KeyCloak API'
  sonarExclusions: ""
  imageName: keycloak-v1

jobs:
  call-reusable-workflow:
    uses: felipementel/reusable-workflows/.github/workflows/sandbox.yml@main
    permissions:
      contents: read # Necessário para checkout
      packages: write # Necessário para o job push-image publicar a imagem Docker no GitHub Packages (ghcr.io)
      security-events: write # Necessário para fazer upload de resultados do Snyk ou Gitleaks para o GitHub Code Scanning/Security
    with:
      environment: ${{ inputs.environment }}
      git-leaks: ${{ inputs.git-leaks }}
      sonar-qube: ${{ inputs.sonar-qube }}
      unit-tests: ${{ inputs.unit-tests }}
      snyk: ${{ inputs.snyk }}
      msg-canal-deploy: ${{ inputs.msg-canal-deploy }}
      dotnetVersion: ${{ vars.dotnetVersion }}
      projectBaseDir: ${{ vars.projectBaseDir }}
      sln: ${{ vars.sln }}
      mainProject: ${{ vars.mainProject }}
      reportTitle: ${{ vars.reportTitle }}
      sonarExclusions: ${{ vars.sonarExclusions }}
      imageName: ${{ vars.imageName }}
    secrets: inherit
